apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  name: example-dataimportcron
  annotations:
    "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
spec:
  garbageCollect: Outdated
  schedule: 55 2/12 * * *
  managedDataSource: rhel-guest-custom
  template:
    metadata: {}
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/boukhano/rhel-guest-custom:9.5
      storage:
        resources:
          requests:
            storage: 30Gi
    status: {}
